import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const sourceDir = path.join(repoRoot, "src", "dll", "ui", "assets", "inputs");
const pngDir = path.join(repoRoot, "src", "dll", "ui", "assets", "inputs_png");
const rawDir = path.join(repoRoot, "src", "dll", "ui", "assets", "inputs_raw");
const iconSize = 96;

async function ensureDir(dirPath) {
  await fs.mkdir(dirPath, { recursive: true });
}

async function rasterizeOne(svgPath) {
  const baseName = path.basename(svgPath, ".svg");
  const pngPath = path.join(pngDir, `${baseName}.png`);
  const rawPath = path.join(rawDir, `${baseName}.rgba`);

  const basePipeline = sharp(svgPath, { density: 512 }).resize(iconSize, iconSize, {
    fit: "contain",
    background: { r: 0, g: 0, b: 0, alpha: 0 },
  });

  await basePipeline.clone().png().toFile(pngPath);
  const { data, info } = await basePipeline.clone().ensureAlpha().raw().toBuffer({ resolveWithObject: true });
  if (info.width !== iconSize || info.height !== iconSize || info.channels !== 4) {
    throw new Error(`Unexpected raster size for ${baseName}: ${info.width}x${info.height}x${info.channels}`);
  }
  await fs.writeFile(rawPath, data);
}

async function main() {
  await ensureDir(pngDir);
  await ensureDir(rawDir);

  const entries = await fs.readdir(sourceDir, { withFileTypes: true });
  const svgFiles = entries
    .filter((entry) => entry.isFile() && entry.name.toLowerCase().endsWith(".svg"))
    .map((entry) => path.join(sourceDir, entry.name))
    .sort((a, b) => a.localeCompare(b));

  for (const svgPath of svgFiles) {
    await rasterizeOne(svgPath);
  }

  const readme = [
    "Generated by: node tools/rasterize_inputs.mjs",
    `Source: ${path.relative(repoRoot, sourceDir)}`,
    `Size: ${iconSize}x${iconSize} RGBA`,
    "",
  ].join("\n");
  await fs.writeFile(path.join(rawDir, "README.txt"), readme, "utf8");
  console.log(`Rasterized ${svgFiles.length} SVG files to PNG and RGBA.`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
