import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const sourcePngDir = path.join(repoRoot, "src", "dll", "ui", "assets", "inputs_png");
const sourceSvgDir = path.join(repoRoot, "src", "dll", "ui", "assets", "inputs");
const targetPngDir = path.join(repoRoot, "landing-page", "assets", "inputs_png");
const targetSvgDir = path.join(repoRoot, "landing-page", "assets", "inputs_svg");

async function ensureEmptyDir(dirPath) {
  await fs.rm(dirPath, { recursive: true, force: true });
  await fs.mkdir(dirPath, { recursive: true });
}

async function copyFilteredFiles(sourceDir, targetDir, extension) {
  const entries = await fs.readdir(sourceDir, { withFileTypes: true });
  const files = entries
    .filter((entry) => entry.isFile() && entry.name.toLowerCase().endsWith(extension))
    .map((entry) => entry.name)
    .sort((a, b) => a.localeCompare(b));

  for (const fileName of files) {
    await fs.copyFile(path.join(sourceDir, fileName), path.join(targetDir, fileName));
  }
  return files.length;
}

async function main() {
  await ensureEmptyDir(targetPngDir);
  await ensureEmptyDir(targetSvgDir);

  const pngCount = await copyFilteredFiles(sourcePngDir, targetPngDir, ".png");
  const svgCount = await copyFilteredFiles(sourceSvgDir, targetSvgDir, ".svg");

  const readme = [
    "Landing page move icon assets.",
    "Generated by: node tools/sync_landing_assets.mjs",
    "Source PNG: src/dll/ui/assets/inputs_png",
    "Source SVG: src/dll/ui/assets/inputs",
    "",
  ].join("\n");

  await fs.writeFile(path.join(repoRoot, "landing-page", "assets", "README.txt"), readme, "utf8");
  console.log(`Synced landing assets: ${pngCount} PNG + ${svgCount} SVG`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
